# Generated by Django 5.0 on 2024-01-11 02:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("AppCuentos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cuento",
            name="fecha_creacion",
        ),
    ]
