# Generated by Django 5.0 on 2024-01-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCuentos", "0002_remove_cuento_fecha_creacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuento",
            name="autor",
            field=models.CharField(max_length=200),
        ),
    ]
