# Generated by Django 5.0 on 2024-01-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("AppCuentos", "0003_alter_cuento_autor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historia",
            name="autor",
            field=models.CharField(
                help_text="Nombre del autor o autores de la historia", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="historia",
            name="contenido",
            field=models.TextField(help_text="Contenido de la historia"),
        ),
        migrations.AlterField(
            model_name="historia",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Fecha y hora de creación de la historia"
            ),
        ),
        migrations.AlterField(
            model_name="historia",
            name="puntuacion",
            field=models.IntegerField(default=0, help_text="Puntuación de la historia"),
        ),
        migrations.AlterField(
            model_name="historia",
            name="titulo",
            field=models.CharField(help_text="Título de la historia", max_length=200),
        ),
    ]
